### ISSUE TITLE
Quick start not running properly

### ISSUE THREAD

**Issue by chariot1498** [daochenzha/autosmote#1]
I tried running the quick start routine. After cloning the repo and installing requirements.txt I ran: python3 train.py
I got a value error. I am attaching the screenshot for this
<img width="1017" alt="Screen Shot 2022-11-27 at 10 02 56 PM" src="https://user-images.githubusercontent.com/20710774/204182479-bf207b7a-63d9-4e62-82ff-b92c60e1bd7a.png">

**Comment by daochenzha** [comment]
@chariot1498 Thanks for the feedback. This could be caused by gym version. Could you try removing these codes?

https://github.com/daochenzha/autosmote/blob/main/autosmote/rl/env.py#L70-L74

**Comment by chariot1498** [comment]
So I removed the (dtype=bool) line for next and it seems to work. I do end up with a macro F1 score of 0.552 on Mozilla4. Is that the expected behaviour?

**Comment by daochenzha** [comment]
@chariot1498 Yes, it is. The result has some variance. It is better to run multiple times.

**Comment by chariot1498** [comment]
Closing the issue since the proposed solution works
